version: '3.8'
services:
  yunohost:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    restart: always
    container_name: yunohost
    hostname: yunohost.local
    ports:
      - '2022:22'
      - '2025:25'
      - '2080:80'
      - '20443:443'
      - '2465:465'
      - '2587:587'
      - '2993:993'
      - '5222:5222'
      - '5269:5269'
    command: ["/bin/systemd"]
    volumes:
      # - '/srv/yuno/backup:/home/yunohost.backup/archives'
      - '/media:/media'
      # - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      # - '/var/run/docker.sock:/var/run/docker.sock'
