#!/bin/bash
if [ -f "/etc/yunohost/installed" ]
then
    true
else
    service dnsmasq restart
    service slapd restart
    service nscd restart
    service nslcd restart
    service metronome restart
    service nginx restart
    DOMAIN=`hostname -d`    
    #echo '127.0.0.1 ip.yunohost.org' >> /etc/hosts    
    cat << EOF > /etc/dnsmasq.d/$DOMAIN
resolv-file=
#address=/$DOMAIN/127.0.0.3
txt-record=$DOMAIN,"v=spf1 mx a -all"
mx-host=$DOMAIN,$DOMAIN,5
srv-host=_xmpp-client._tcp.$DOMAIN,$DOMAIN,5222,0,5
srv-host=_xmpp-server._tcp.$DOMAIN,$DOMAIN,5269,0,5
srv-host=_jabber._tcp.$DOMAIN,$DOMAIN,5269,0,5
EOF
    echo "127.0.0.3 $DOMAIN" >> /etc/hosts 
    rm /sbin/iptables
    rm /sbin/ip6tables
    ln -s /bin/true /sbin/iptables
    ln -s /bin/true /sbin/ip6tables
    yunohost tools postinstall -d $DOMAIN -p yunohost || true
    yunohost tools postinstall -d $DOMAIN -p yunohost
fi

exit 0
